services:
  - type: web
    name: spring-h2-app
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/evento-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
